server:
  port: ${EUREKA_SERVER_PORT:8761}
management:
  port: 8082
  security:
    enabled: false
eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0
    enableSelfPreservation: false
---
spring:
  profiles: development
server:
  port: ${EUREKA_SERVER_PORT:8761}
management:
  port: 8082
  security:
    enabled: false
eureka:
  instance:
    hostname: ${vcap.application.uris[0]}
    nonSecurePort: 80
    preferIpAddress: true
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0
    enableSelfPreservation: false